const mongoose = require('mongoose')
const userSchema = new mongoose.Schema({
userName:{
type:String,
required:true,
unique:true
},
firstName:{
type:String,
required:true
},
type:String,
lastName:{
type:String,
required:true
},
middleName:{
type:String
},
email:{
type:String,
required:true,
unique:true,
match: /[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/
},
lastVisited:{
type:Date,
default:Date()
},
image:{
    type:String,
    default:'image'
},
isAdmin:{
type:Boolean,
default:false
},
reports:[],
phone1:String,
phone2:String,
gender:{
type:String
},
currentCity:{
type:String
},
password:{
type:String,
required:true,
min:8,
max:100
},
usedPasswords:[],
country:String,
date:{
type:Date,
default:Date()
},
secondaryName:String,
degree:String,
nickName:String,
orcidDef:String,
position:String,
institution1:String,
department:String,
institution2:String,
streetAddress:String,
city:String,
state:String,
code:String,
classification:[],
password:String,
fax:String,
orcid:String,
title:String,
sentMessages:[],
receivedMessages:[],
status:{
type:String,
default:'active'
}
},{timestamps:true})
module.exports = mongoose.model('User',userSchema)